### ISSUE TITLE
this  sortware don't work on yak-3

### ISSUE THREAD

**Issue by ToniCui** [MeSoftHorny/WTRTI#1]
It can't read the fuel status of the USSR yak-3, I can't see how many fuel left. Since I don't have the France version , I don't know if it works on that one. Anyway thanks for making this, it's awsome and really helpful.Thanks!

**Comment by MeSoftHorny** [comment]
Yes, on Yak-3(and some other planes), indicators "Fuel m:s" and "Fuel consumption" will not work. But "Mass of Fuel" should work. Because localhost:8111 doesn't have "fuel" parameter(for this plane), which has better precision(compare to "Mfuel") for calculation fuel consumption and remain of fuel.

**Comment by ToniCui** [comment]
> Yes, on Yak-3(and some other planes), indicators "Fuel m:s" and "Fuel consumption" will not work. But "Mass of Fuel" should work. Because localhost:8111 doesn't have "fuel" parameter(for this plane), which has better precision(compare to "Mfuel") for calculation fuel consumption and remain of fuel.

Thanks for your reply and the explanation, now I fully understand why it doesn't work. And thank again for this magnificant plug-in software.
