### ISSUE TITLE
Displaying Calculated fields

### ISSUE THREAD

**Issue by Garbey** [MeSoftHorny/WTRTI#10]
Is there a way to get WTRTI to run simple calculations and display them? (OSD: WTRTI)
Because i would like to know the sine of my pitch `SIN(Pitch)`, which is something i cannot do in my head.

Reasoning:
![image](https://user-images.githubusercontent.com/54438566/138970259-68602523-29ce-4fe7-afbe-9edd8ae5437d.png)
In this image you can see i have locked a target on my radar, and i have an approximate pitch from my location; so i can work out the altitude difference.
![image](https://user-images.githubusercontent.com/54438566/138971392-45cc4715-2432-43b5-92e0-26875e30952d.png)

**Comment by MeSoftHorny** [comment]
Lua scirpts implemented in v2.0.
