### ISSUE TITLE
XP-50 - Incorrect altitude readings.

### ISSUE THREAD

**Issue by HypheX** [MeSoftHorny/WTRTI#13]
When using the XP-50, WTRTI displays the wrong altitude, approximately every 10k feet, it goes back to 0. I suspect that it is due to the localhost data being different from other aircraft.

**Comment by MeSoftHorny** [comment]
Yes. I'm aware of this bug. Due the lack of **altitude_10k** in localhost, the app only uses **altitude_hour**.

**Comment by MeSoftHorny** [comment]
In v2.0, "Altitude, m/ft"  uses "H, m" instead.
