### ISSUE TITLE
Auto Load Profile For Helicopters

### ISSUE THREAD

**Issue by ashton-01** [MeSoftHorny/WTRTI#14]
Right now there is only an option to switch HUD's between propeller aircraft and jet aircraft, could you add another for helicopters? Thanks.

**Comment by MeSoftHorny** [comment]
This is already implemented in v1.8.
Priority of auto-loading:
    1. Vehicle Profiles.
    2. By a Type(Fighter, Strike, etc).
    3. By a propulsion (Prop, Jet).

Here is the latest version:
https://github.com/MeSoftHorny/WTRTI/releases/tag/v1.8.2

**Comment by ashton-01** [comment]
Oh my bad, I didn't have the newest version. Thanks!
