### ISSUE TITLE
Abnormal display of MSI Afterburner on WTRTI's OSD

### ISSUE THREAD

**Issue by Trisolarans0** [MeSoftHorny/WTRTI#15]
When running afterburner and WTRTI at the same time, Afterburner's data will be displayed on WTRTI's OSD, which blocks the War Thunder's flight data display, and there is no way to adjust the location of Afterburner's data.
![QQ图片20220427164648(1)](https://user-images.githubusercontent.com/59606177/165480149-d455902f-d956-4f30-a5b9-384ef93dace3.jpg)

**Comment by MeSoftHorny** [comment]
WTRTI's OSD uses OpenGL for rendering, so Afterburner(RTSS) detects it as a 3d software.
You can add an exclusion for WTRTI in RTSS, with <Shift>+<Add profile> and select only WTRTI.
