### ISSUE TITLE
Some players reported that the account was logged in abnormally after using this plugin

### ISSUE THREAD

**Issue by congup** [MeSoftHorny/WTRTI#16]
More than one player responded to the question。
Have you considered releasing the source code for players to review?

**Comment by MeSoftHorny** [comment]
May be they using VPN(or proxy) and forgot to turn it off.
did they download the app from here? 
it would be nice if they checked the executable file for a checksum, the original v1.8.2 has:
SHA256: a8930829a3da048945ac06244c53188a6c0214b5fc3db82e21f39915cda72681

> Have you considered releasing the source code for players to review?
In the near future, no. Actually, it won''t really help, 99.9999% users will download a binary file anyway.
