### ISSUE TITLE
State Window Not Opening

### ISSUE THREAD

**Issue by seennotheard** [MeSoftHorny/WTRTI#17]
Running v1.8.2, I have tried pressing F2 in every single WTRTI window, and I am unable to get the state window to appear. I have also tried fn + F2.

**Comment by seennotheard** [comment]
So, it appears that you cannot open the state window after clicking on the table of indicators on the main menu, until you minimize and reopen the window. You must click on the grey area.

**Comment by MeSoftHorny** [comment]
> So, it appears that you cannot open the state window after clicking on the table of indicators on the main menu, until you minimize and reopen the window. You must click on the grey area.

Yeah, there will be a fix in version 2.0
