### ISSUE TITLE
"Thrust to Weight" and "Total mass" indicators not working

### ISSUE THREAD

**Issue by ashton-01** [MeSoftHorny/WTRTI#19]
Database is updated and states the empty weight and fuel weight of the aircraft however it reads 0.00 on the indicators.
![image](https://user-images.githubusercontent.com/54195925/187235960-f3191e59-21ed-4428-8ade-353c86154c54.png)
![image](https://user-images.githubusercontent.com/54195925/187236079-e4bfb0db-158a-4870-be25-8be6d8e9aaa3.png)

**Comment by MeSoftHorny** [comment]
For these indicators, you have to enable "FM mode" in Settings->Advanced, and add **enableFMCommands:b=yes** to the config.blk file. 
More detailed instructions are in the **README.txt** file.

**Comment by ashton-01** [comment]
Alright, thank you for clarifying.
