### ISSUE TITLE
Is the source code available? 

### ISSUE THREAD

**Issue by YabbaTroll** [MeSoftHorny/WTRTI#2]
Title.

The "Source code (zip)" only contains a readme file. I was planning on experimenting with making a version of this with native vr support kinda like https://www.youtube.com/watch?v=oGrpFZQ9zrc&feature=youtu.be

**Comment by MeSoftHorny** [comment]
No, the source code is closed. Can't say when it will be available.
BTW, I recently started researching about VR. And I think, I can try to implement VR support by myself.

**Comment by YabbaTroll** [comment]
Sure thing.

**Comment by arbitur** [comment]
Why is the source code closed? Arent you the owner of the code?

**Comment by MeSoftHorny** [comment]
> Why is the source code closed?
The time has not come yet.

> Arent you the owner of the code?
Yes, I'm the owner of the source code. That's why I can decide to open it or not.

**Comment by arbitur** [comment]
> The time has not come yet.

What does that mean? What is blocking?

**Comment by MeSoftHorny** [comment]
> What does that mean? What is blocking?

That means that the code will be closed, until I decide to make it open.
