### ISSUE TITLE
Can't set hotkeys

### ISSUE THREAD

**Issue by Jayhawker32** [MeSoftHorny/WTRTI#20]
osd_show_toggle_hotkey=0x0 and every other hotkey setting showing 0x0 even after setting a hotkey in the program.

**Comment by MeSoftHorny** [comment]
Hello.
There is a bug in v2.0. Some keys not working or saving.
I fixed most of them in version 2.0.1 (coming soon), but it would be nice if you could let me know what a key you are trying to set, so I could double-check it.

**Comment by Jayhawker32** [comment]
Numpad decimal, should be 0x6E on the virtual keyboard

**Comment by MeSoftHorny** [comment]
Thanks. Yes, I fixed it. Please wait for the release of v2.0.1.

**Comment by Jayhawker32** [comment]
Great thanks!

**Comment by MeSoftHorny** [comment]
Fixed in the v2.0.1
