### ISSUE TITLE
Request RPM% custom variable for helicopters

### ISSUE THREAD

**Issue by ZdrytchX** [MeSoftHorny/WTRTI#22]
A useful but missing variable for helicopters is the RPM% indication. Without it, the user has to declare alerts for every helicopter with a unique engine/rotor system and so a manual database for RPM ranges would be useful.

There is an instrument for it but the majority of the indicators in helicopters are broken.

**Comment by MeSoftHorny** [comment]
Something like "Critical RPM, %"? 
RPM / "max RPM" ?

**Comment by ZdrytchX** [comment]
Yeah, pretty much.

Something on the side note, I still have no idea how to create custom variables, is that still a WIP feature or is it just not available through the user interface?

**Comment by MeSoftHorny** [comment]
You mean a custom indicator? Ability create custom indicators were added in v1.8, and in the v2.0 there is possible to use lua-scripts for custom value processing.
To create a new indicator: **open "Add" window(+ button)** -> **click RMB on the list** - > **New**
After setup, press OK button, and the new indicator with '[U]' will be added to the "Add" list.

**Comment by MeSoftHorny** [comment]
Implemented in v2.1
