### ISSUE TITLE
Black background

### ISSUE THREAD

**Issue by JustCauseWhyNot** [MeSoftHorny/WTRTI#23]
Would it be possible to use mangohud, vkbasalt, or any other linux overlays as the osd? Because I've got a black instead of transparent background when using the builtin osd. I'm also using dwm which may cause some issues since I can't run wt in windowed fullscreen.

**Comment by MeSoftHorny** [comment]
> Would it be possible to use mangohud, vkbasalt, or any other linux overlays as the osd?

No, these overlays do not provide any API for external use, such as RTSS does on Windows, especially vkbasalt, it's only post-processing vulkan layer.

> Because I've got a black instead of transparent background when using the builtin osd.

For transparency, you have to enable Compositor (Compton, Picom, Kwin).

**Comment by JustCauseWhyNot** [comment]
> No, these overlays do not provide any API for external use, such as RTSS does on Windows, especially vkbasalt, it's only post-processing vulkan layer.

Thanks for the response. I didn't know that, but makes sense 
> For transparency, you have to enable Compositor (Compton, Picom, Kwin).

Would it be possible to not need a compositor? Thanks for informing me.

**Comment by JustCauseWhyNot** [comment]
Thank you for the comprehensive response.
