### ISSUE TITLE
Request: Set Colored Keywords in Battle Log

### ISSUE THREAD

**Issue by Le0nWolf** [MeSoftHorny/WTRTI#24]
Hello, can you please add the function to set Keywords in the Battle Log? So that I can set for example my username to color red, and the keyword destroyed  to green so that I can better track what happens in Game on my second screen. Or I can set additionally the username of my girlfriend to the color purple to track what she does in battle. This function would be awesome.

**Comment by MeSoftHorny** [comment]
Yes, I think so.

**Comment by MeSoftHorny** [comment]
Implemented in v2.1
