### ISSUE TITLE
How to make a separate alarm for engines?

### ISSUE THREAD

**Issue by Ford3l** [MeSoftHorny/WTRTI#26]
How to make sure that the siren was separately on engines?

**Comment by MeSoftHorny** [comment]
To set an alert condition for a specific engine? Unfortunately, there is no way to do that. Maybe in the future I'll make this possible through the dependency condition.

**Comment by Ford3l** [comment]
I really want this, i will be very grateful if you make this thing

**Comment by MeSoftHorny** [comment]
Implemented in v2.2
