### ISSUE TITLE
Sound alerts stacking configuration options

### ISSUE THREAD

**Issue by ZdrytchX** [MeSoftHorny/WTRTI#28]
If you reuse an identicle sound file in multiple alert zones, with spaced out periods they ideally shouldn't stack when crossing between alert zones.

Let's say alert zone 1 is 10->13, and zone 2 is 13+. Zone 1 has the sound occur every 5 seconds, and zone 2 has the sound occur every 2 seconds.

But let's say the number is increasing quickly by 3 every second. What will end up happening is the alert will be played on the 1st and 2nd second, while after that it will only play every 2 seconds as intended.

##Configuration option suggestions:

* Don't stack sounds globally (throughout the entire WT RTI software, so play the warnings sequentially while multiple alerts are active similar to WT-Betty's restricted playback, there could be an option within each indicator that tells it that it is a lower priority alert for being pushed to the back of the queue, or lowest priority alert so that it wouldn't be added to the queue if there are other alerts going on)  
* Don't stack all sounds within this indicator  (use the shortest period between alert zones, so in the above example, the alert should sound every 2 seconds, even if the second alert uses a different sound file)  
* Don't stack unique sounds (as above, however when playing a new sound alert, cut the first one prematurely to allow the new sound to play earlier)  (should be the default option?)
* Don't stack unique sounds but queue them sequentially (so the previous sound isn't cut prematurely)
* Allow sound alert stacking  (as it is currently)

**Comment by MeSoftHorny** [comment]
Ok. I'll see what I can do.

P.S. Sorry for the late reply.
