### ISSUE TITLE
FlightModel files

### ISSUE THREAD

**Issue by LucasFeliciano21** [MeSoftHorny/WTRTI#3]
Hi man, 

first of all, very nice job there, your work is just amazing. 

I'm building a Hotas and I wanted to put the WEP indicator up on it, as this data from the wep available for the planes are only present on the flight model files I wonder if it's possible for you to share with me where can I get the updates FM files so I can harvest that information. That would be very useful for me

Many thanks!

**Comment by MeSoftHorny** [comment]
Sure. 
Here is frequently updated github repo:
https://github.com/gszabi99/War-Thunder-Datamine
