### ISSUE TITLE
Simplytranslate.org Down - In-App Chat Translation Option No Longer Works

### ISSUE THREAD

**Issue by chemputer** [MeSoftHorny/WTRTI#30]
Using the "In-App Translation" for the Game Chat function does not work, and it looks to be due to [Simplytranslate.org](https://simplytranslate.org) being down. Attempting to load the website leads to a connection reset page, and while the project (if they are the same), still seems to be up and running, it's available at [a different URL hosted by pussthecat](https://simplytranslate.pussthecat.org/)

So if you try to use the functionality in the app it just sits at "Downloading Instances" indefinitely, and of course does not work for translating in-game text via the app. See the image below.
![WTRTI_773MiFeyPS](https://user-images.githubusercontent.com/46601333/234979980-007865bd-803c-47cb-b2d1-b0cc6a53ad08.png)

**Comment by MeSoftHorny** [comment]
Well... In this case, I think I'll replace it with [lingva.ml](lingva.ml).

Thanks for noticing it.

**Comment by MeSoftHorny** [comment]
The simplytranslate.org has been replaced by lingva.ml in v2.1.2
