### ISSUE TITLE
Compatibility issues with Vulkan schema

### ISSUE THREAD

**Issue by 573741451** [MeSoftHorny/WTRTI#32]
Hello, have you considered improving compatibility with Vulkan mode?

Screen menu type :WTRTI
If the game is launched in Vulkan mode, data will not be displayed on the screen，any data

DX11 and DX12 display normally

**Comment by 573741451** [comment]
One more question.
After running the plugin for a period of time. The computer will experience a network outage situation.In the lower right corner of the taskbar, the connection is normal, but it is actually disconnected

**Comment by MeSoftHorny** [comment]
It looks like the game with Vulkan is working in "Exclusive Fullscreen" mode, ignoring "Fullscreen windowed" mode setting.
Unfortunately, there is no easy-fix on my end.

> After running the plugin for a period of time. The computer will experience a network outage situation.In the lower right corner of the taskbar, the connection is normal, but it is actually disconnected

Are you sure the app is the cause? 
What does the Event Viewer tells you? (https://www.windowscentral.com/how-use-event-viewer-windows-10)

**Comment by 573741451** [comment]
I'm sure

**Comment by 573741451** [comment]
> It looks like the game with Vulkan is working in "Exclusive Fullscreen" mode, ignoring "Fullscreen windowed" mode setting. Unfortunately, there is no easy-fix on my end.
> 
> > After running the plugin for a period of time. The computer will experience a network outage situation.In the lower right corner of the taskbar, the connection is normal, but it is actually disconnected
> 
> Are you sure the app is the cause? What does the Event Viewer tells you? (https://www.windowscentral.com/how-use-event-viewer-windows-10)

Actually, I don't seem to be the only one with this problem

**Comment by 573741451** [comment]
> It looks like the game with Vulkan is working in "Exclusive Fullscreen" mode, ignoring "Fullscreen windowed" mode setting. Unfortunately, there is no easy-fix on my end.
> 
> > After running the plugin for a period of time. The computer will experience a network outage situation.In the lower right corner of the taskbar, the connection is normal, but it is actually disconnected
> 
> Are you sure the app is the cause? What does the Event Viewer tells you? (https://www.windowscentral.com/how-use-event-viewer-windows-10)

However, you updated version 2.1.2. So far, I have not had any disconnection problem for an hour，2.1.1 and 2.0 will have problems for half an hour to an hour

**Comment by MeSoftHorny** [comment]
> However, you updated version 2.1.2. So far, I have not had any disconnection problem for an hour，2.1.1 and 2.0 will have problems for half an hour to an hour

Hmm... I've updated the network library in this version, maybe it did the trick.
If this happens again, try looking for it in the Event Viewer.
