### ISSUE TITLE
no mac version

### ISSUE THREAD

**Issue by failed101** [MeSoftHorny/WTRTI#33]
i have no idea how to make it work with make if it doesnt have a mac version, it might be hard to do but support you for this is a great add on

**Comment by MeSoftHorny** [comment]
Try using the Windows version with Wine. The overlay feature will not work, but everything else should work fine (sound alerts, logging, etc).

**Comment by failed101** [comment]
is there any way to make a mac version? i can test it out and such if you do want to head down that road

**Comment by MeSoftHorny** [comment]
Release [v2.3](https://github.com/MeSoftHorny/WTRTI/releases/tag/v2.3)
