### ISSUE TITLE
No overlay shows up on linux?

### ISSUE THREAD

**Issue by Sheepss** [MeSoftHorny/WTRTI#34]
Since there is no actual "how to" I assume I just start the program and it should work? if so, it's not showing up at all

**Comment by MeSoftHorny** [comment]
On Linux, the compositor (kwin, compiz, etc.) must be enabled for the overlay to work.
What DE are you using?

**Comment by Sheepss** [comment]
Im on Mint 21.1

**Comment by MeSoftHorny** [comment]
Try turning off the "Disable compositing for full-screen windows" in "System Settings" -> "General" (Preferences section).
Like on this picture: https://fosspost.org/wp-content/uploads/2019/09/2019-09-07_22-48.png.webp
Than restart.

**Comment by Sheepss** [comment]
Sorry for the late reply, First off that worked so thanks. New problem, it is now only on the left monitor and I can't move it to the main monitor.  or at least don't know how, lol

**Comment by MeSoftHorny** [comment]
Try this version, and tell me if it works: 
[WTRTI_v2.1.2_x1_linux64.zip](https://github.com/MeSoftHorny/WTRTI/files/12068424/WTRTI_v2.1.2_x1_linux64.zip)

**Comment by Sheepss** [comment]
Yep, that works. shows up on the correct monitor. Thank you very much :D

**Comment by MeSoftHorny** [comment]
The v2.2 is released.
