### ISSUE TITLE
WTRTI needs to be closed using task manager and relaunched when restarting the game

### ISSUE THREAD

**Issue by someonemax** [MeSoftHorny/WTRTI#35]
Hi,
When closing and relaunching the game, WTRTI will stop working and even right clicking on the tray icon doesn't open the context menu, so you have to close it using task manager, and relaunch it.

**Comment by MeSoftHorny** [comment]
Hi.
Does this happen every time? Can you please provide the WTRTI.cfg file? I'll check it.

**Comment by someonemax** [comment]
Yes
The WTRTI is still responsive (context menu opens) when I close the game. But if I relaunch the game, WTRTI freezes and has to be closed using task manager.
BTW Won't you make a new topic on the new forums? 

[myWTRTI_2023-06-10-00.zip](https://github.com/MeSoftHorny/WTRTI/files/11929773/myWTRTI_2023-06-10-00.zip)

**Comment by MeSoftHorny** [comment]
Did a quick check... seems to work fine.
When you open Task Manager, how much CPU/Mem is the WTRTI using?

**Comment by MeSoftHorny** [comment]
> BTW Won't you make a new topic on the new forums?

I don't know... I hate the "game activity" rules on the forums, and a new forum looks awful.
I will probably make a discord channel, for communication purposes.

**Comment by someonemax** [comment]
<img width="329" alt="image" src="https://github.com/MeSoftHorny/WTRTI/assets/76533230/829048f5-879d-4f88-b585-365bb9c7e804">


> Did a quick check... seems to work fine. When you open Task Manager, how much CPU/Mem is the WTRTI using?

**Comment by MeSoftHorny** [comment]
Is it when it freezes?
Have you tried a fresh install? I mean, start the app in a different folder.

**Comment by someonemax** [comment]
Yes 
Is there a debug feature that I can enable to generate logs for you?

**Comment by MeSoftHorny** [comment]
Unfortunately no (at least in the release build).
In this case, having a log may not really help. 
It looks like there's a deadlock(multi-thread issue), and it's hard to detect without a proper debugging tool.

How long have you been experiencing this issue? Have you tried different versions?

**Comment by someonemax** [comment]
I will need to test the previous versions to tell you at which version this has started.

But as a potential solution, isn't it possible to check if the program is responsive or not, when a new instance of the program opens, and if it's not, for it to kill it and start the new instance?
i.e. Instead of having to manually close it using task manager, whenever you launch WTRTI, it will check if a previous instance is running, and if it is responsive, and if it's not responsive it will kill it and launch a new instance

**Comment by someonemax** [comment]
Or just always kill the running instance and run a new instance whenever the user (re)launches WTRTI

**Comment by MeSoftHorny** [comment]
> But as a potential solution, isn't it possible to check if the program is responsive or not, when a new instance of the program opens, and if it's not, for it to kill it and start the new instance?
> i.e. Instead of having to manually close it using task manager, whenever you launch WTRTI, it will check if a previous instance is running, and if it is responsive, and if it's not responsive it will kill it and launch a new instance

I'll see what can be done. 
Right now I'm curious why this is happening. Because I can't reproduce it on my system.

**Comment by someonemax** [comment]
I did some more testing to intentionally reproduce it and in hindsight I probably should've mentioned this

I use a TV for the game and when I lock the PC and leave the system AFK, the TV turns off automatically after some time and Windows will set the monitor as primary display and if I unlock the PC before I manually turn the TV back on, it will move all the windows (game and presumably WTRTI) to the monitor (though it is possible to move the game back to the TV by setting it to full screen then full windowed again).

If I manually turn on the TV before I unlock the PC, this will not happen (and the game will still be on the TV after unlocking the PC). But for some reason game's performance will take a hit so I have to relaunch it and upon relaunch WTRTI is not working. 
I just tested it by manually turning off the TV after locking the PC and WTRTI seems to go unresponsive even before relaunching the game.

**Comment by MeSoftHorny** [comment]
I still can't reproduce it. 
Please try this version:  [WTRTI_v2.1.2_x1_windows.zip](https://github.com/MeSoftHorny/WTRTI/files/12068400/WTRTI_v2.1.2_x1_windows.zip)

**Comment by someonemax** [comment]
I tested it several times with each version and it seems to be fixed in the new one. Can reproduce it reliably with old version but can't reproduce it with the new version.
Thanks

**Comment by MeSoftHorny** [comment]
Good. Thanks.

**Comment by someonemax** [comment]
While WTRTI now works after the whole "Display turning off and on again" thing, the GPU usages will go way up and causes stutters.

<img width="532" alt="Screenshot 2023-07-23 183018" src="https://github.com/MeSoftHorny/WTRTI/assets/76533230/b3af8d26-05b3-4874-b7db-eaea40e0d351">

Closing WTRTI and relaunching it fixes it. 

<img width="534" alt="Screenshot 2023-07-23 183124" src="https://github.com/MeSoftHorny/WTRTI/assets/76533230/d469f284-10c8-487b-be3f-d7eb68de6472">

**Comment by MeSoftHorny** [comment]
Does this happen when you go into battle/test flight or immediately after turning off the display?
Is the overlay displayed correctly?
Can you please try to open the settings window(WTRTI) and press OK button, does that fix the high GPU usage?

**Comment by someonemax** [comment]
It happens after I go into test flight or battle.

Before going into battle:

<img width="531" alt="Screenshot 2023-07-24 185048" src="https://github.com/MeSoftHorny/WTRTI/assets/76533230/f1e32c77-17ed-4039-b31b-532a30460684">


In the battle:


<img width="530" alt="Screenshot 2023-07-24 185208" src="https://github.com/MeSoftHorny/WTRTI/assets/76533230/bbe9b8ee-b2b1-4477-8781-6f0fe920a5f2">


After restarting WTRTI:

<img width="530" alt="Screenshot 2023-07-24 185301" src="https://github.com/MeSoftHorny/WTRTI/assets/76533230/8c32e07d-821a-48f7-80ed-88b3958273c6">


As for whether overlay is displayed correctly, if I turn off the display when the system is still unlocked, and turn it back on, the game will be moved to secondary display, but can be moved back to main display by switching display mode to windowed then back to full window, and then WTRTI will be displayed but will be off center (seems like to stay centered around the display that the game was automatically moved to, after turning off the main display)

But if I turn off the display and turn it back on, while the system is locked, then unlock the system, WTRTI overlay will be displayed correctly (As presumably Windows will not move the game to another display, if the main display turns off when the system is locked)

**Comment by MeSoftHorny** [comment]
Well... But what about the "Settings & OK button"? Have you tried that?

**Comment by someonemax** [comment]
Sorry, forgot about that one ...

1- Just going into settings and pressing OK doesn't fix it.
2- Going into settings and changing theme under General tab and pressing OK doesn't fix it.
3- Going into settings and into OSD tab, Disabling "Show OSD" then pressing OK doesn't fix it.
4- Going into settings and into OSD tab, Enabling "Hide unavailable indicators" then pressing OK doesn't fix it.
5- Going into settings and into OSD tab, enabling "Show units in OSD" then pressing OK fixes it.
6- Going into settings and into OSD tab, changing Window mode from Borderless to Windowed then pressing OK fixes it.

**Comment by MeSoftHorny** [comment]
Thanks.
Hmm, intertesing results... I'll take a look as soon as possible.

**Comment by MeSoftHorny** [comment]
Here, try this version: :  [WTRTI_v2.1.2_x2_windows.zip](https://github.com/MeSoftHorny/WTRTI/files/12173239/WTRTI_v2.1.2_x2_windows.zip)

**Comment by someonemax** [comment]
Yes this fixes it
Thanks

**Comment by MeSoftHorny** [comment]
The v2.2 is released.

**Comment by someonemax** [comment]
Seems like this bug is back with v2.2.1:

![image](https://github.com/MeSoftHorny/WTRTI/assets/76533230/a795f8f6-e789-42b6-aee1-38c462534af2)
