### ISSUE TITLE
Link to forum broken

### ISSUE THREAD

**Issue by downloadpizza** [MeSoftHorny/WTRTI#36]
Since Gaijin has killed the old forum the link is dead. Maybe a Discord would be nice, but I can see how thats moderation overhead and would remove time budget from the project.

**Comment by MeSoftHorny** [comment]
Yeah... I changed the link to the old (archived) forum. When I have time, I'll try to move all the information here (to the Wiki section).
For communication, I guess I could create a discord, but I personally won't be able to visit it very often.

**Comment by MeSoftHorny** [comment]
Discord server: https://discord.gg/XAEYmRM5NG

**Comment by downloadpizza** [comment]
Thank you. You do not need to waste your time on the discord, just having other WTRTI users and being able to exchange with them makes the discord very nice. Thanks and closing
