### ISSUE TITLE
Oil radiator percentage display broken

### ISSUE THREAD

**Issue by trexwyoming379** [MeSoftHorny/WTRTI#37]
Oil radiator % displays as 0% on the OSD and N/A on the app. This is a problem for planes that have separately controllable oil radiators. 
I am using v2.1.2 windows

**Comment by MeSoftHorny** [comment]
Some planes have this in-game 'bug', when there is controllable oil radiators, but there is no data on web-map (localhost:8111).
Anyway, can you provide a names of the planes? I'll check it.

**Comment by trexwyoming379** [comment]
So far I have found that it doesn't work for the: P-400, P-39N-0, P-39Q-5, P-38E, P-38G-1, P-63A-5, P-63A-10, P-63C-5, P-38J-15, P-38L-5-LO, P-51C-10, P-47D-22-RE, P-47D-25, P-47D-28, P-51D-5, P-51D-30, P-47N-15, F4F-3, F4F-4, F4U-1A, F4U-1A (USMC), F4U-1D, F4U-1C, F4U-4, F4U-4B, F8F-1, F8F-1B, F7F-1, SB2U-2, SB2U-3, SBD-3, TBF-1C, A-20G-25, A-26B-10, A-26B-50, AM-1, AD-2, AD-4, PBY-5, PBY-5A, B-18A, PBM-1, B-34, P-47M-1-RE, F2G-1, every Bf 109, every Yak-9, every Yak-3, both I-185s, all La-5,s both La-7s, La-9, Sea Fury FB 11, Tempest Mk II, A7M2, J2M2, all Ki-43s, both Ki-44s, all Ki-61s, Ki-100

There are definitely more, I just got tired of looking for them, since it works for some planes like the F6F-5, F6F-5N, I-225, and every Zero, you're probably right about it just being that not all planes report their oil radiators to localhost:8111

**Comment by MeSoftHorny** [comment]
Tested some of them. Yes, the prolem in the localhost.

**Comment by trexwyoming379** [comment]
Alright then, I guess there's nothing that can be done if the issue is with localhost:8111. 
Thanks for responding so quickly and figuring out what the issue was.
