### ISSUE TITLE
Unable to display/log data other than numbers.

### ISSUE THREAD

**Issue by Daedheldir** [MeSoftHorny/WTRTI#45]
It's impossible to display other data than numbers. 

Being able to log values other that numbers would make it easier to perform data analysis using tools like excel pivot tables / power bi (e.g. combining logs into one file and filtering based on aircraft type / name / other attributes)
***
E.g. we create a new indicator to log aircraft type:
![Screenshot 2023-11-16 143329](https://github.com/MeSoftHorny/WTRTI/assets/44434382/fce9c314-7dec-4f71-8aab-d40089399858)

In OSD / WTRTI it displays 0 instead of the string value from the State.
![Screenshot 2023-11-16 143724](https://github.com/MeSoftHorny/WTRTI/assets/44434382/2c27370b-e6d3-4014-b357-8dfbd1a03e60)
![Screenshot 2023-11-16 143848](https://github.com/MeSoftHorny/WTRTI/assets/44434382/a9d1e4e9-519d-450b-a1e0-fd6e92e2296c)
***
The same happens when using Lua, it is impossible to display even a simple char:

`function value_proc(in_value, value_idx)
   return 'a', true
end`

![Screenshot 2023-11-16 144133](https://github.com/MeSoftHorny/WTRTI/assets/44434382/41039ef3-f718-4380-8fde-270a7b23e740)

***

`function value_proc(in_value, value_idx)
   return 10, true
end`

![Screenshot 2023-11-16 144234](https://github.com/MeSoftHorny/WTRTI/assets/44434382/4d2cf896-b1f7-4d84-a363-e723b0b45a26)

**Comment by MeSoftHorny** [comment]
Yes, it's currently limited to numbers only. 
The text 'values' in my todo-list.  I will see if I have time to implement this in v2.3.

**Comment by MeSoftHorny** [comment]
Implemented in v2.3
