### ISSUE TITLE
The name of each item is not displayed

### ISSUE THREAD

**Issue by Langyinnan** [MeSoftHorny/WTRTI#46]
![屏幕截图 2023-11-19 005533](https://github.com/MeSoftHorny/WTRTI/assets/128231679/38f90056-61b0-467b-bf71-094df5e84786)

**Comment by MeSoftHorny** [comment]
Make sure the font **SourceHanSansCN-Normal** is installed and selected in the **Settings -> OSD -> Aa**
![wtrti_font_select](https://github.com/MeSoftHorny/WTRTI/assets/60583341/a1b35758-a44e-432e-8486-c575e4fee039)

**Comment by MeSoftHorny** [comment]
#21

**Comment by Langyinnan** [comment]
> #21



> 确保在“**设置”-“OSD”-“> Aa**”中安装并选择了字体**SourceHanSansCN-Normal**> ![wtrti_font_select](https://user-images.githubusercontent.com/60583341/284016763-a1b35758-a44e-432e-8486-c575e4fee039.PNG)

Yes, it can be displayed but there is overlap
![Uploading 屏幕截图 2023-11-24 193551.png…]()

**Comment by Langyinnan** [comment]
> Make sure the font **SourceHanSansCN-Normal** is installed and selected in the **Settings -> OSD -> Aa** ![wtrti_font_select](https://user-images.githubusercontent.com/60583341/284016763-a1b35758-a44e-432e-8486-c575e4fee039.PNG)

Yes, it can be displayed but there is overlap

**Comment by Langyinnan** [comment]
![屏幕截图 2023-11-24 193551](https://github.com/MeSoftHorny/WTRTI/assets/128231679/cb476b63-e577-428b-9650-db41b7d11b46)

**Comment by MeSoftHorny** [comment]
Try to increase this option:
![wtrti_value_align](https://github.com/MeSoftHorny/WTRTI/assets/60583341/42008eac-ea2d-4d63-a0fd-cc8ce55f49d4)

**Comment by Langyinnan** [comment]
> Try to increase this option: ![wtrti_value_align](https://private-user-images.githubusercontent.com/60583341/285538732-42008eac-ea2d-4d63-a0fd-cc8ce55f49d4.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NzQ4ODksIm5iZiI6MTcwMDg3NDU4OSwicGF0aCI6Ii82MDU4MzM0MS8yODU1Mzg3MzItNDIwMDhlYWMtZWEyZC00ZDYzLWEwZmQtY2M4Y2U1NWY0OWQ0LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDAxMDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmODFmOTAyMGQ4MWU0NWY2ODVlYzc2NTg0YmRlZTQwYjNmNjA1MTY0NTMxZDMwY2M2NmUwZmZkOTlhYTRkNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wgCsMH2OiSEoZS47SbwoQUeqmRhg9dk1PKHlMhRZtTU)

Thanks it works
