### ISSUE TITLE
Overlay with gamescope

### ISSUE THREAD

**Issue by Sheepss** [MeSoftHorny/WTRTI#47]
Any way to get the actual overlay working with gamescope enabled?

the only way to use it with gamescop is by changing the overlay to windowed, which does get annoying as everytime you spawn in a plane your game unfocuses to the wtrti window.

**Comment by MeSoftHorny** [comment]
Gamescope support will be added in a future update. Currently it is only available in WIP version (TBD).
![wt_gamescope_test](https://github.com/MeSoftHorny/WTRTI/assets/60583341/6f1d384d-aa06-4bf1-8a2d-233787086d5d)

**Comment by Sheepss** [comment]
thanks for the info and i'm glad you are working on it.
