### ISSUE TITLE
warthunder screen goes black when I try to run WTRTI

### ISSUE THREAD

**Issue by CrypticPotatoo** [MeSoftHorny/WTRTI#52]
hi, I have a problem where if I run WTRTI my war thunder screen goes black, there is some visible parts of the game around the edge of the screen and sounds etc still works. if I close WTRTI it goes back to normal, I cannot figure out why its doing this and any help would be awesome, cheers

**Comment by CrypticPotatoo** [comment]
it was working fine a week or so ago

**Comment by MeSoftHorny** [comment]
Hi. Try reinstalling GPU drivers.
BTW, can you tell what OS you are using and what version of the GPU driver?

**Comment by CrypticPotatoo** [comment]
hey mate, I'm using windows 11 pro 64bit, my GPU drivers are AMD version 31.0.23013.1023 I think, I somehow got it working yesterday but its doing it again, i reinstalled the drivers and nothing changed cheers

**Comment by MeSoftHorny** [comment]
Hmm, looks like they made some changes in OpenGL for this version (WTRTI uses OpenGL for rendering):
![amd_drivers](https://github.com/MeSoftHorny/WTRTI/assets/60583341/8c12f1e9-6035-4226-b7f7-2253346b6057)

Unfortunately, I can't reproduce it, because I can't install this version of the driver on my PC (I have only old iGPU vega).

Can you try to rollback to a previous version (eg. **23.11.1**)?

**Comment by CrypticPotatoo** [comment]
Sure, I'll give it a crack later on and let you know how I go

**Comment by HypheX** [comment]
> Sure, I'll give it a crack later on and let you know how I go
Hey, just wondering if you've gotten around to testing this yet?

**Comment by CrypticPotatoo** [comment]
hey mate sorry, I struggled to backdate the drivers (AMD things) but the update for the drivers that came out yesterday has seemed to fix everything

**Comment by HypheX** [comment]
> hey mate sorry, I struggled to backdate the drivers (AMD things) but the update for the drivers that came out yesterday has seemed to fix everything

That's great to hear! I'm glad the issue has been resolved :)
