### ISSUE TITLE
custom indicator doesnt return floatpoint

### ISSUE THREAD

**Issue by HerpesHabenderHauptmannHarry** [MeSoftHorny/WTRTI#53]
In settings of custom indicator precision is set to 2
As test i set return to 100.52, overlay shows 101

**Comment by MeSoftHorny** [comment]
Try increasing the “Precision” in the indicator settings and in the “Custom Indicator” editor.

**Comment by HerpesHabenderHauptmannHarry** [comment]
set it to max 5 still doesnt work

**Comment by HerpesHabenderHauptmannHarry** [comment]
oop nevermind found the indicator settings works now
