### ISSUE TITLE
Feature Request: CAS indicator

### ISSUE THREAD

**Issue by obama** [MeSoftHorny/WTRTI#55]
When the battle log mentions a plane/Heli mark <player> as CAS.
When chat reads "Air alerts! heading / altitude" mark <player> as CAS
when <player> dies, unmark as CAS.

while (CAS) FLASH(ENEMY PLANE/HELI IS IN AIR)

it would help you be aware if there is a plane still up

**Comment by MeSoftHorny** [comment]
Sorry, I won't be doing any enemy related features.
