### ISSUE TITLE
WTRTI For Imac

### ISSUE THREAD

**Issue by Leifkon** [MeSoftHorny/WTRTI#56]
Good morning, I wanted to ask if there is any option to use this program for iMac, since the ones available are for Linux and Windows and cannot be used on Mac. Do you know if there is any alternative or if you are working to release a version for Mac as well ? Thanks and best regards

**Comment by MeSoftHorny** [comment]
Hey. I'm currently developing a MacOS version. 
Find me on Discord (\_avb\_) if you want to participate in testing.

**Comment by MeSoftHorny** [comment]
discord server: https://discord.gg/XAEYmRM5NG

**Comment by MeSoftHorny** [comment]
Released [v2.3](https://github.com/MeSoftHorny/WTRTI/releases/tag/v2.3)
