### ISSUE TITLE
Will not disable HUD display when using ground vehicle

### ISSUE THREAD

**Issue by freeAbrams** [MeSoftHorny/WTRTI#57]
Version: 2.3
After release 2.3, in game HUD display will not disable when using a ground vehicle, both hanger and in-game. It will correctly disable when using a ship.

**Comment by MeSoftHorny** [comment]
Yes, I am aware of the issue. The fix is coming soon.

**Comment by MeSoftHorny** [comment]
fixed in v2.3.1
