### ISSUE TITLE
Overlay not working with Vulkan renderer

### ISSUE THREAD

**Issue by xFluffyDemon** [MeSoftHorny/WTRTI#61]
It'll flicker for a seconf when alt tabbing, but does not show when game is in "focus"

Steam Vulkan commnad promp `-forcestart -driver:vulkan`

**Comment by MeSoftHorny** [comment]
checked, works fine.
![wt_vulkan_wtrti](https://github.com/user-attachments/assets/d4d87f13-6c65-45b6-b024-6d067a0557f0)

**Comment by xFluffyDemon** [comment]
Idk whats happening then
![Screenshot_507](https://github.com/user-attachments/assets/9e4250ad-cbc1-449a-b766-36e5c77c80e2)
![Screenshot_506](https://github.com/user-attachments/assets/32916edd-09fc-457a-b871-df8068194197)

**Comment by MeSoftHorny** [comment]
Make sure the game is running in "Fullscreen Window" mode, also check that the executable (aces.exe) doesn't have "Disable fullscreen optimizations" turned on.

**Comment by MeSoftHorny** [comment]
Oh, since you have RTSS installed, take a look at the DesktopOverlayHost application(in the RTSS root folder).
If this overlay doesn't appear over the game, it means the game is running in exclusive fullscreen mode.

**Comment by xFluffyDemon** [comment]
> Make sure the game is running in "Fullscreen Window" mode, also check that the executable (aces.exe) doesn't have "Disable fullscreen optimizations" turned on.

Everything is as it should be



> Oh, since you have RTSS installed, take a look at the DesktopOverlayHost application(in the RTSS root folder). If this overlay doesn't appear over the game, it means the game is running in exclusive fullscreen mode.

Switching to RTSS in OSD type seems to fix it, altough i cant move Groups around apart from the top/default one.

Did you run the same arguments as me to get vulkan working?

**Comment by MeSoftHorny** [comment]
> Switching to RTSS in OSD type seems to fix it, altough i cant move Groups around apart from the top/default one.
You don't need to change the OSD type, just check that the DesktopOverlayHost overlay(draggable pink window) is displayed over the game.

> Did you run the same arguments as me to get vulkan working?
Yes

**Comment by xFluffyDemon** [comment]
> You don't need to change the OSD type, just check that the DesktopOverlayHost overlay(draggable pink window) is displayed over the game.

This seems to be the issue, but ingame and the config.blk both show "Fullscreen Window", even tried -popupwindow comand and still nothing. apart from the overlays the game seems to be running in "Fullscreen Window" ie Alt tabing or pressing windows key the game remains in the background and doesnt minimize.

At this point im not sure its a WTRTI problem so feel free to close the issue if you think the same

**Comment by MeSoftHorny** [comment]
Yeah. I think so too.
