### ISSUE TITLE
WTRTI Causing AMD Driver Crash

### ISSUE THREAD

**Issue by domikoni** [MeSoftHorny/WTRTI#62]
Hi. I apologize if this is not the right place for this. I am getting a consistent AMD driver crash while running the game with WTRTI open. It seems to happen more reliably in test drive, happening after anywhere from 5-10 minutes of gameplay. The game will freeze, and the frozen frame will kaleidoscope and then CTD with an AMD driver crash notification. I suppose I'm not 100% sure it's WTRTI causing the issue, but I have been able to play for 8+ hours at a time without it without a crash, so I'm fairly confident. 

Additionally, I've had it "soft crash" where the whole screen will go black, but I can still hear the game and control it. Additionally there is a single pixel width line around the outside of the screen where the game is visible, but otherwise completely black. If I ALT+Tab I can see the game, but as soon as I ALT+Tab back in, the black screen comes back. Closing WTRTI fixes this immediately and I can even restart it and continue playing.

Things I have tried:

Updating from AMD 23.12.1 to latest 24.8.1 driver
Using both Direct3D and OpenGL renderers
Running the game at lower graphics settings
Running the game with and without vsync/freesync

I'm not really sure what else to try. Any assistance would be greatly appreciated. Thanks.

===================

Specs:

Windows 10 Pro 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)
12th Gen Intel(R) Core(TM) i9-12900K (24 CPUs), ~3.2GHz
AMD Radeon RX 7900 XT
ASUS PRIME Z970-V WiFi
2x16 RAM@4800MHz with XMP
ASUS XG49VQ running at a custom resolution of 3238x1080@144hz for War Thunder FoV nonsense

[DxDiag.txt](https://github.com/user-attachments/files/16971110/DxDiag.txt)

**Comment by MeSoftHorny** [comment]
can you provide WTRTI.cfg file from Profiles folder?

**Comment by MeSoftHorny** [comment]
Closing. No respond
